- name: Tap Homebrew cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  become: no

- name: Brew unlink terraform
  ansible.builtin.shell:
    cmd: brew unlink terraform  

- name: Install applications
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ apps }}'
  become: no