---
- name: Install Applications from Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item }}'
    state: latest
  loop: '{{ apps }}'
  # become: yes
  # become_user: cloud_user
  # become_method: runas